gui:
  mouseEvents: true
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexable
  sidePanelWidth: 0.3333
  scrollPastBottom: true
  theme:
  activeBorderColor:
    - '#cba6f7'
    - bold
  inactiveBorderColor:
    - '#a6adc8'
  optionsTextColor:
    - '#89b4fa'
  selectedLineBgColor:
    - '#313244'
  cherryPickedCommitBgColor:
    - '#45475a'
  cherryPickedCommitFgColor:
    - '#cba6f7'
  unstagedChangesColor:
    - '#f38ba8'
  defaultFgColor:
    - '#cdd6f4'
  searchingActiveBorderColor:
    - '#f9e2af'
  authorColors:
    '*': '#b4befe'

git:
  paging:
    useConfig: false
    pager: delta --dark --paging=never
    colorArg: always
notARepository: quit
disableStartupPopups: false
promptToReturnFromSubprocess: false
