#! /bin/sh

sxhkd -c $HOME/.config/sxhkd/bspwm-hotkeys &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4
bspc config window_gap   0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc rule -a 1Password:\* state=floating follow=on center

bspc config focused_border_color #80ffdb

function merge_borders {
  BW=4
  # Overlapping borders
  bspc config border_width $BW
  bspc config window_gap -$BW
  for side in top right bottom left; do
    bspc config ${side}_padding $BW
  done
}
